### ISSUE TITLE
Question, not an issue

### ISSUE THREAD

**Issue by josheigel** [scottbedard/analyticsextension#6]
Hey man, I'm really sorry to bug you, but I've just been trying to track down some issues in my site. For this analytics extension, did you ever use a vendor library React for promises? I appreciate the help!

**Comment by scottbedard** [comment]
Hey, no worries. Sorry but no, I did not use React for this project. The various charts are coming straight from October core.

**Comment by josheigel** [comment]
Ok, thanks. Sorry to take your time!
